/**
 * Wire format for event batch. Identical for Variant A (proxy) and Variant B (SDK).
 */
export interface EventBatch {
  /** UUID generated by the recorder */
  session_id: string;
  /** User identifier from the app */
  distinct_id: string;
  /** Monotonically increasing, per session */
  batch_seq: number;
  /** base64(gzip(JSON.stringify(eventWithTime[]))) */
  events_b64_gzip: string;
}

export interface SessionMeta {
  session_id: string;
  distinct_id: string;
  started_at: string;
  last_batch_at: string;
  batch_count: number;
}
