/**
 * Wire format for event batch (POST /s/).
 * user_id is NOT in the wire format — the server derives it from the auth cookie.
 */
export interface EventBatch {
  /** UUID generated by the recorder */
  session_id: string;
  /** Monotonically increasing, per session */
  batch_seq: number;
  /** base64(gzip(JSON.stringify(eventWithTime[]))) */
  events_b64_gzip: string;
}

export interface SessionMeta {
  session_id: string;
  /** Derived server-side from the auth cookie at first batch */
  user_id: string;
  started_at: string;
  last_batch_at: string;
  batch_count: number;
}
